
require 'rubygems'
require 'bundler/setup'
require 'rspec/core/rake_task'
require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'
require File.join(File.dirname(__FILE__), 'app')

task :default => :test
task :test => :spec

if !defined?(RSpec)
	puts "RSpec is missing"
else
	desc "Run all examples"
	RSpec::Core::RakeTask.new(:spec) do |t|
		t.pattern = Dir['spec/**/*_spec.rb']
	end
end

